/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  interpreterSidebar: [{type: 'autogenerated', dirName: 'interpreter'}],
  graphicsSidebar: [{type: 'autogenerated', dirName: 'graphics'}],
  frontendSidebar: [{type: 'autogenerated', dirName: 'frontend'}],
  webSidebar: [{type: 'autogenerated', dirName: 'fullstack'}],
  wlxSidebar: [{type: 'autogenerated', dirName: 'wlx'}]

  // But you can create a sidebar manually
  
  /*tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['interpreter/intro'],
    },
  ],*/
   
};

module.exports = sidebars;
